# Generated by Django 5.0.2 on 2024-03-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='myimages',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
